name: Generate Heylogs Demo Cast and SVG

on:
  workflow_dispatch: 

jobs:
  build-heylogs-demo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v7

    - name: Set up JBang
      uses: jbangdev/setup-jbang@main

    - name: Trust heylogs catalog
      run: jbang trust add https://github.com/nbbrd/

    - name: Create heylogs alias
      run: |
        jbang app setup
        jbang app install heylogs@nbbrd

    - uses: charmbracelet/vhs-action@v2.1.0
      with:
        path: 'demo.tape'

    - name: Upload Generated Assets
      uses: actions/upload-artifact@v7
      with:
        name: heylogs-demo-media
        path: |
          examples/demo.gif
