name: Generate Heylogs Demo Cast and SVG

on:
  workflow_dispatch: 

jobs:
  build-heylogs-demo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v7

    - name: Set up JBang
      uses: jbangdev/setup-jbang@main

    - name: Trust heylogs catalog
      run: jbang trust add https://github.com/nbbrd/

    - name: Create heylogs alias
      run: |
        jbang app setup
        jbang app install heylogs@nbbrd

#    - run: docker run --rm -v $PWD:/vhs ghcr.io/charmbracelet/vhs demo.tape

    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Install and run VHS and Dependencies
      run: |
        brew install vhs ttyd ffmpeg
        run: vhs < demo.tape

    - name: Upload Generated Assets
      uses: actions/upload-artifact@v7
      with:
        path: demo.gif
        archive: false
